### ISSUE TITLE
can some one help me ?

### ISSUE THREAD

**Issue by OnlyReihe** [nasirjd/foodmine-react-js#4]
whenever I'm trying to update profile 

Request failed with status code 401
AxiosError: Request failed with status code 401
    at settle (http://localhost:3000/static/js/bundle.js:75770:12)
    at XMLHttpRequest.onloadend (http://localhost:3000/static/js/bundle.js:74452:66)

this error is popping up
![Screenshot 2023-12-14 171456](https://github.com/nasirjd/foodmine-react-js/assets/96999914/0f17f04a-4335-40a7-9a57-4f4f8ffada74)

**Comment by OnlyReihe** [comment]
while opening go to payment page the same thing is happening
![Screenshot 2023-12-14 174649](https://github.com/nasirjd/foodmine-react-js/assets/96999914/76af2233-9976-4ca4-9cf5-74d9450223f1)

**Comment by ErdhyErnando** [comment]
Also encountered an axios error, it worked a few days ago but now it didn't :(
![Screenshot 2024-01-23 130330](https://github.com/nasirjd/foodmine-react-js/assets/121667726/9698b493-a890-4dba-bcfe-f041e48e3323)
